/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    fontFamily: {
      sans: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
      mono: ['Geist Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
    },
    extend: {
      colors: {
        'subject-physics':   'hsl(var(--subject-physics))',
        'subject-biology':   'hsl(var(--subject-biology))',
        'subject-chemistry': 'hsl(var(--subject-chemistry))',
        'subject-earth':     'hsl(var(--subject-earth))',
        surface:             'hsl(var(--surface))',
        foreground:          'hsl(var(--foreground))',
        background:          'hsl(var(--background))',
        border:              'hsl(var(--border))',
        ring:                'hsl(var(--ring))',
        muted:               'hsl(var(--muted))',
        'muted-foreground':  'hsl(var(--muted-foreground))',
        primary:             'hsl(var(--primary))',
        'primary-foreground':'hsl(var(--primary-foreground))',
        secondary:           'hsl(var(--secondary))',
        'secondary-foreground':'hsl(var(--secondary-foreground))',
        destructive:         'hsl(var(--destructive))',
        'destructive-foreground':'hsl(var(--destructive-foreground))',
        success:             'hsl(var(--success))',
        'success-foreground':'hsl(var(--success-foreground))',
        warning:             'hsl(var(--warning))',
        'warning-foreground':'hsl(var(--warning-foreground))',
        card:                'hsl(var(--card))',
        'card-foreground':   'hsl(var(--card-foreground))',
        accent:              'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
      },
      borderRadius: {
        sm:  '6px',
        DEFAULT: '8px',
        md:  '8px',
        lg:  '10px',
        xl:  '12px',
        '2xl': '16px',
        '3xl': '20px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0,0,0,0.04)',
        sm: '0 1px 2px rgba(0,0,0,0.06), 0 1px 1px rgba(0,0,0,0.04)',
        DEFAULT: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.05)',
        md: '0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
        lg: '0 8px 24px rgba(0,0,0,0.10), 0 2px 6px rgba(0,0,0,0.05)',
        popover: '0 12px 32px rgba(0,0,0,0.16), 0 2px 8px rgba(0,0,0,0.08)',
      },
      animation: {
        'slide-up':   'slideUp 0.2s cubic-bezier(0.16,1,0.3,1)',
        'fade-in':    'fadeIn 0.15s ease',
        'spin-slow':  'spin 3s linear infinite',
      },
      keyframes: {
        slideUp:   { from: { transform: 'translateY(6px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        fadeIn:    { from: { opacity: '0' }, to: { opacity: '1' } },
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
